service: github-check

app: serverless-challenges
tenant: lukelafountaine

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    GITHUB_WEBHOOK_SECRET: very_very_secret
    GITHUB_APP_PRIVATE_KEY: ${s3:github-check-private-key-secret/silvermine-es-lint-checker.2018-11-23.private-key.pem}
    IS_LAMBDA: true

functions:
 check:
  handler: handler.check
  events: 
   - http: 
      path: check
      method: post
